---

- name: Configure OvS DPDK
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  tasks:
    - name: Configure OvS DPDK configs
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ovs_dpdk
      tags:
        - edpm_ovs_dpdk
